Make redirects permanent
niteoweb/pyramid_redirect pull request #1
Opened 2019-04-25 07:03 UTC by am-on

Change HTTP status code of redirects to 301.

2019-04-25 07:07 UTC, dmurko approved these changes

2019-04-25 07:56 UTC, dmurko commented
302 gets indexed, 301 should not as per below sources.

https://www.quora.com/Why-is-Google-indexing-301-redirection-pages
https://moz.com/community/q/google-is-indexing-my-301-redirects-to-other-sites

2019-04-26 07:14 UTC, zupo commented
302 is dangerous because browsers cache them. If you muck them up, there is no way to fix it other than telling all your visitors to clear their entire browser cache (which is impossible). 

There needs to be a way to specify which type of a redirect you want to do.

2019-04-26 07:14 UTC, zupo requested changes
301 are dangerous because browsers cache them. If you muck them up, there is no way to fix it other than telling all your visitors to clear their entire browser cache (which is impossible).

There needs to be a way to specify which type of a redirect you want to do. Then you always do 302 first, leave it in production for a week, then switch over to 301.

2019-04-26 07:28 UTC, dmurko commented
If it helps: I don't see a use case for temporary (302) redirect, and we've never used it intentionally in the past.

2019-04-26 08:40 UTC, zupo commented on pyramid_redirect/__init__.py
> +                if perament:
typo `perament`

2019-04-26 08:41 UTC, zupo commented
@am-on: please add docs that `permanent` redirects are dangerous because they get stored in visitors local browser caches that cannot be purged so if you do them wrong you are in pile of trouble. Recommend people use 301 for a few days and only then switch over to 302.

2019-04-26 08:52 UTC, zupo commented
Mixed up 302 and 301. Fixed my comments.

2019-04-26 09:38 UTC, am-on commented
@zupo It looks like browsers stopped caching 301 redirects. 
>Tested 301 redirect caching 02/2019 using Chrome 72, Firefox 65, UC Browser 7, Chromium 41 (for no real reason other than I had it installed!), latest version of Chrome on Android, latest version of Safari on iPhone, IE11 and Edge.
>
>None of the browsers cached the 301s!
>https://www.epiphanysearch.co.uk/thoughts/do-modern-browsers-still-cache-301-redirects

2019-08-22 06:59 UTC, zupo commented
@am-on: do we still need this?

2019-08-22 07:10 UTC, am-on commented
@zupo would be nice to have for minisites

2019-08-22 07:16 UTC, merged

2019-08-22 07:16 UTC, zupo commented
I'll cut a release then.

2019-08-22 07:26 UTC, zupo commented
https://pypi.org/project/pyramid_redirect/0.3/